services:
  db:
    container_name: mysql-db-mcsv
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin3it
      MYSQL_DATABASE: db-mcsv-iplacex
      MYSQL_USER: db-mcsv-3it
      MYSQL_PASSWORD: admin3it
    ports:
      - "3306:3306"
    
volumes:
  db-data: